Hebb rule:
$$\tau_W \frac{dW}{dt} = QW$$ 
$Q = uu^T$:input correlation matrix, u:input, W: weight, v:output, 
$$v=Wu=W^Tu=u^TW \\
W(t) = \sum_i c_i(0)x^{\lambda_i t/ \tau_W} e_i$$
$e_i$ and $\lambda_i$ are eigenvector and eigenvalues of Q

In [1]:
import numpy as np

In [2]:
Q=np.array([[0.2,0.1],[0.1,0.15]])

In [3]:
Q

array([[0.2 , 0.1 ],
       [0.1 , 0.15]])

In [4]:
l,e = np.linalg.eig(Q)

In [5]:
l

array([0.27807764, 0.07192236])

In [6]:
e

array([[ 0.78820544, -0.61541221],
       [ 0.61541221,  0.78820544]])

In [7]:
e[:,0]

array([0.78820544, 0.61541221])

In [11]:
-2*e[:,0] #this principle eigenvector dominates after a long time (some constant and e_i)

array([-1.57641088, -1.23082442])