Hebb rule:
$$\tau_W \frac{dW}{dt} = QW$$ 
$Q = uu^T$:input correlation matrix, u:input, W: weight, v:output, 
$$v=Wu=W^Tu=u^TW \\
W(t) = \sum_i c_i(0)x^{\lambda_i t/ \tau_W} e_i$$
$e_i$ and $\lambda_i$ are eigenvector and eigenvalues of Q

In [14]:
import numpy as np

In [3]:
Q=np.array([[0.2,0.1],[0.1,0.3]])

In [4]:
Q

array([[0.2, 0.1],
       [0.1, 0.3]])

In [5]:
l,e = np.linalg.eig(Q)

In [6]:
l

array([0.1381966, 0.3618034])

In [7]:
e

array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]])

In [8]:
e[:,1]

array([-0.52573111, -0.85065081])

In [10]:
-2*e[:,1] #this principle eigenvector dominates after a long time (some constant and e_i)

array([1.05146222, 1.70130162])