In [1]:
from __future__ import division
import numpy as np
import matplotlib.pyplot as plt

import pickle

In [2]:
FILENAME = 'pop_coding.pickle'

with open(FILENAME, 'rb') as f:
    data = pickle.load(f)

data.keys()

dict_keys(['c1', 'r1', 'r3', 'c2', 'c3', 'r2', 'c4', 'r4'])

In [3]:
data['c1'] # basis vector of neuron 1

array([0.70710678, 0.70710678])

In [4]:
data['r1'] # the respons (firing rate in Hz) of the neuron1 to this mystery stimulus. 10 trials.

array([11.9, 12.8, 13.9, 12.1, 11.3, 12.2, 12.9, 12.4, 13.2, 10.7])

In [24]:
r_mean_n1 = sum(data['r1'])/10
r_mean_n1

12.340000000000002

In [17]:
data['r2']

array([18.8, 18. , 19. , 19.1, 18.1, 21.5, 20.3, 21.2, 18.6, 20.4])

In [25]:
r_mean_n2 = sum(data['r2'])/10
r_mean_n2

19.5

In [18]:
data['r3']

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
data['r4']

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
data['c1'] # basis vector of neuron 1

array([0.70710678, 0.70710678])

In [21]:
data['c2']

array([ 0.70710678, -0.70710678])

In [22]:
data['c3']

array([-0.70710678, -0.70710678])

In [23]:
data['c4']

array([-0.70710678,  0.70710678])

In [10]:
FILENAME_tuning = 'tuning.pickle'

with open(FILENAME_tuning, 'rb') as f:
    data_tuning = pickle.load(f)

data_tuning.keys()

dict_keys(['neuron4', 'stim', 'neuron3', 'neuron2', 'neuron1'])

In [13]:
r_max_n1 = np.max(sum(data_tuning['neuron1'],2)/100)
r_max_n1

31.726999999999997

In [14]:
r_max_n2 = np.max(sum(data_tuning['neuron2'],2)/100)
r_max_n2

21.08900000000001

In [15]:
r_max_n3 = np.max(sum(data_tuning['neuron3'],2)/100)
r_max_n3

15.280000000000006

In [16]:
r_max_n4 = np.max(sum(data_tuning['neuron4'],2)/100)
r_max_n4

27.096

In [26]:
# population vector

vec = ((r_mean_n1 / r_max_n1) * data['c1']) + ((r_mean_n2 / r_max_n2) * data['c2'])
vec

array([ 0.92885252, -0.37880381])

In [40]:
np.arctan(0.37880381 / 0.92885252)*180 / 3.14

22.197827251021856

In [38]:
90 + 22 # degree

112

In [41]:
1/np.sqrt(2)

0.7071067811865475