In [1]:
import numpy as np

In [2]:
M=np.array([[-0.5,0,0.5,0.5,0],[0,-0.5,0,0.5,0.5],[0.5,0,-0.5,0.0,0.5],[0.5,0.5,0,-0.5,0],[0,0.5,0.5,0,-0.5]])

In [3]:
M

array([[-0.5,  0. ,  0.5,  0.5,  0. ],
       [ 0. , -0.5,  0. ,  0.5,  0.5],
       [ 0.5,  0. , -0.5,  0. ,  0.5],
       [ 0.5,  0.5,  0. , -0.5,  0. ],
       [ 0. ,  0.5,  0.5,  0. , -0.5]])

In [4]:
val, vec = np.linalg.eig(M)

In [5]:
val

array([-1.30901699, -0.19098301,  0.5       , -1.30901699, -0.19098301])

In [6]:
vec

array([[ 0.63245553, -0.63245553,  0.4472136 , -0.13661647,  0.37958642],
       [ 0.19543951,  0.51166727,  0.4472136 , -0.62951707, -0.0097433 ],
       [-0.51166727, -0.19543951,  0.4472136 , -0.25244648, -0.36382142],
       [-0.51166727, -0.19543951,  0.4472136 ,  0.47349657,  0.59841873],
       [ 0.19543951,  0.51166727,  0.4472136 ,  0.54508345, -0.60444042]])

In [7]:
W = np.array([[0.6, 0.1, 0.1, 0.1, 0.1],[0.1, 0.6, 0.1, 0.1, 0.1],[0.1, 0.1, 0.6, 0.1, 0.1],[0.1, 0.1, 0.1, 0.6, 0.1],[0.1,0.1,0.1,0.1,0.6]])

In [8]:
W

array([[0.6, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.6, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.6, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.6, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.6]])

In [9]:
u = np.array([0.6, 0.5, 0.6, 0.2, 0.1])

In [10]:
h = np.dot(W,u)

In [11]:
h

array([0.5 , 0.45, 0.5 , 0.3 , 0.25])

In [12]:
e1 = np.dot(h,vec[:,0])/(1-val[0])

In [13]:
e2 = np.dot(h,vec[:,1])/(1-val[1])

In [14]:
e3 = np.dot(h,vec[:,2])/(1-val[2])

In [15]:
e4 = np.dot(h,vec[:,3])/(1-val[3])

In [16]:
e5 = np.dot(h,vec[:,4])/(1-val[4])

In [17]:
np.dot(e1,vec[:,0]) + np.dot(e2,vec[:,1])+np.dot(e3,vec[:,2])+np.dot(e4,vec[:,3])+np.dot(e5,vec[:,4])

array([0.89470203, 0.80867335, 0.82115282, 0.78421698, 0.69125481])